// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CustomerCore.Context
{
    public partial class Address
    {
        public Address()
        {
            Orders = new HashSet<Orders>();
        }

        public int Id { get; set; }
        public int? CustomerId { get; set; }
        public byte? CountryId { get; set; }
        public short? CityId { get; set; }
        public int? TownId { get; set; }
        public int? DistrictId { get; set; }
        public string PostalCode { get; set; }
        public string AddressText { get; set; }

        public virtual Cities City { get; set; }
        public virtual Countries Country { get; set; }
        public virtual Customers Customer { get; set; }
        public virtual Districts District { get; set; }
        public virtual Towns Town { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}