// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CustomerCore.Context
{
    public partial class Categories
    {
        public Categories()
        {
            Items = new HashSet<Items>();
        }

        public int Id { get; set; }
        public int? ParentId { get; set; }
        public string Category { get; set; }
        public bool? IsTheMostChild { get; set; }

        public virtual ICollection<Items> Items { get; set; }
    }
}