// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CustomerCore.Context
{
    public partial class Cities
    {
        public Cities()
        {
            Address = new HashSet<Address>();
            Towns = new HashSet<Towns>();
        }

        public short Id { get; set; }
        public byte CountryId { get; set; }
        public string City { get; set; }

        public virtual Countries Country { get; set; }
        public virtual ICollection<Address> Address { get; set; }
        public virtual ICollection<Towns> Towns { get; set; }
    }
}