// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CustomerCore.Context
{
    public partial class Countries
    {
        public Countries()
        {
            Address = new HashSet<Address>();
            Cities = new HashSet<Cities>();
        }

        public byte Id { get; set; }
        public string Country { get; set; }

        public virtual ICollection<Address> Address { get; set; }
        public virtual ICollection<Cities> Cities { get; set; }
    }
}