// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CustomerCore.Context
{
    public partial class Items
    {
        public Items()
        {
            OrderDetails = new HashSet<OrderDetails>();
            Photos = new HashSet<Photos>();
        }

        public int Id { get; set; }
        public string ItemCode { get; set; }
        public string Item { get; set; }
        public decimal UnitPrice { get; set; }
        public int CategoryId { get; set; }
        public int VatRateId { get; set; }
        public string Brand { get; set; }
        public int Amount { get; set; }

        public virtual Categories Category { get; set; }
        public virtual VatRates VatRate { get; set; }
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual ICollection<Photos> Photos { get; set; }
    }
}