// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CustomerCore.Context
{
    public partial class OrderDetails
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int ItemId { get; set; }
        public int? Amount { get; set; }
        public decimal? UnitPrice { get; set; }
        public decimal? SalePrice { get; set; }

        public virtual Items Item { get; set; }
        public virtual Orders Order { get; set; }
    }
}