// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using static CustomerCore.ViewModels.OrderModels.EditOrderOrderDetailsViewModel;

namespace CustomerCore.Context
{
    public partial class Orders
    {
        public Orders()
        {
            OrderDetails = new HashSet<OrderDetails>();
        }

        public int Id { get; set; }
        public int CustomerId { get; set; }
        public DateTime? Date { get; set; }
        public StatusEnum Status { get; set; }
        public int AddressId { get; set; }

        public virtual Address Address { get; set; }
        public virtual Customers Customer { get; set; }
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
    }
}