// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CustomerCore.Context
{
    public partial class Photos
    {
        public int Id { get; set; }
        public string Photo { get; set; }
        public int ItemId { get; set; }

        public virtual Items Item { get; set; }
    }
}