// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CustomerCore.Context
{
    public partial class Towns
    {
        public Towns()
        {
            Address = new HashSet<Address>();
            Districts = new HashSet<Districts>();
        }

        public int Id { get; set; }
        public short CityId { get; set; }
        public string Town { get; set; }

        public virtual Cities City { get; set; }
        public virtual ICollection<Address> Address { get; set; }
        public virtual ICollection<Districts> Districts { get; set; }
    }
}