// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CustomerCore.Context
{
    public partial class VatRates
    {
        public VatRates()
        {
            Items = new HashSet<Items>();
        }

        public int Id { get; set; }
        public decimal? VatRate { get; set; }

        public virtual ICollection<Items> Items { get; set; }
    }
}